db.definitions.drop()
db.definitions.insert( { word: 'flag', definition: 'ictf{temp_flag_for_testing}' } )
// Everything past here is just to give the app some "real" content, not needed for the challenge
db.definitions.insert( { word: 'default', definition: 'a standard setting especially of computer software, such as of type size or style' } )
db.definitions.insert( { word: 'scissors', definition: 'an instrument used for cutting cloth, paper, and other material, consisting of two blades laid one on top of the other and fastened in the middle so as to allow them to be opened and closed by a thumb and finger inserted through rings on the end of their handles.' } )
db.definitions.insert( { word: 'scrape', definition: 'drag or pull a hard or sharp implement across (a surface or object) so as to remove dirt or other matter' } )
db.definitions.insert( { word: 'evanescent', definition: 'soon passing out of sight, memory, or existence; quickly fading or disappearing' } )
db.definitions.insert( { word: 'bell', definition: 'a city in south-western California, south-east of Los Angeles; population 36,657 (est. 2008).' } )
db.definitions.insert( { word: 'hose', definition: 'a flexible tube conveying water, used chiefly for watering plants and in firefighting' } )
db.definitions.insert( { word: 'representative', definition: 'typical of a class, group, or body of opinion' } )
db.definitions.insert( { word: 'puny', definition: 'small and weak' } )
db.definitions.insert( { word: 'squirrel', definition: 'an agile tree-dwelling rodent with a bushy tail, typically feeding on nuts and seeds.' } )
db.definitions.insert( { word: 'changeable', definition: 'liable to unpredictable variation' } )
db.definitions.insert( { word: 'bite', definition: '(of a person or animal) use the teeth to cut into or through something' } )
db.definitions.insert( { word: 'reign', definition: 'hold royal office; rule as monarch' } )
db.definitions.insert( { word: 'kitty', definition: 'a fund of money for communal use, made up of contributions from a group of people.' } )
db.definitions.insert( { word: 'bee', definition: 'a stinging winged insect which collects nectar and pollen, produces wax and honey, and lives in large communities.' } )
db.definitions.insert( { word: 'repair', definition: 'restore (something damaged, faulty, or worn) to a good condition' } )
db.definitions.insert( { word: 'unhealthy', definition: 'harmful to health' } )
db.definitions.insert( { word: 'hulking', definition: '(of a person or object) very large, heavy, or clumsy' } )
db.definitions.insert( { word: 'overflow', definition: '(especially of a liquid) flow over the brim of a receptacle' } )
db.definitions.insert( { word: 'short', definition: 'measuring a small distance from end to end' } )
db.definitions.insert( { word: 'satisfy', definition: 'meet the expectations, needs, or desires of (someone)' } )
db.definitions.insert( { word: 'charming', definition: 'very pleasant or attractive' } )
db.definitions.insert( { word: 'close', definition: 'only a short distance away or apart in space or time' } )
db.definitions.insert( { word: 'clip', definition: 'a flexible or spring-loaded device for holding an object or objects together or in place' } )
db.definitions.insert( { word: 'army', definition: 'an organized military force equipped for fighting on land' } )
db.definitions.insert( { word: 'basket', definition: 'a container used to hold or carry things, typically made from interwoven strips of cane or wire' } )
db.definitions.insert( { word: 'unfasten', definition: 'open the fastening of; undo (something)' } )
db.definitions.insert( { word: 'prevent', definition: 'keep (something) from happening' } )
db.definitions.insert( { word: 'mass', definition: 'a large body of matter with no definite shape' } )
db.definitions.insert( { word: 'heap', definition: 'an untidy collection of objects placed haphazardly on top of each other' } )
db.definitions.insert( { word: 'divergent', definition: 'tending to be different or develop in different directions' } )
db.definitions.insert( { word: 'unwritten', definition: 'not recorded in writing' } )
db.definitions.insert( { word: 'special', definition: 'better, greater, or otherwise different from what is usual' } )
db.definitions.insert( { word: 'null', definition: 'having no legal or binding force; invalid' } )
db.definitions.insert( { word: 'oil', definition: 'a viscous liquid derived from petroleum, especially for use as a fuel or lubricant.' } )
db.definitions.insert( { word: 'sheet', definition: 'a large rectangular piece of cotton or other fabric, used on a bed to cover the mattress and as a layer beneath blankets when these are used.' } )
db.definitions.insert( { word: 'pine', definition: 'an evergreen coniferous tree which has clusters of long needle-shaped leaves. Many kinds are grown for the soft timber, which is widely used for furniture and pulp, or for tar and turpentine.' } )
db.definitions.insert( { word: 'pear', definition: 'a yellowish- or brownish-green edible fruit that is typically narrow at the stalk and wider towards the base, with sweet, slightly gritty flesh.' } )
db.definitions.insert( { word: 'tick', definition: 'a mark (✓) used to indicate that an item in a list or text is correct or has been chosen, checked, or dealt with.' } )
db.definitions.insert( { word: 'observant', definition: 'quick to notice or perceive things' } )
db.definitions.insert( { word: 'steer', definition: 'guide or control the movement of (a vehicle, vessel, or aircraft), for example by turning a wheel or operating a rudder' } )
db.definitions.insert( { word: 'squash', definition: 'crush or squeeze (something) with force so that it becomes flat, soft, or out of shape' } )
db.definitions.insert( { word: 'wood', definition: 'the hard fibrous material that forms the main substance of the trunk or branches of a tree or shrub, used for fuel or timber' } )
db.definitions.insert( { word: 'push', definition: 'exert force on (someone or something) in order to move them away from oneself' } )
db.definitions.insert( { word: 'hurried', definition: 'done in a hurry; rushed' } )
db.definitions.insert( { word: 'bit', definition: 'a small piece, part, or quantity of something' } )
db.definitions.insert( { word: 'building', definition: 'a structure with a roof and walls, such as a house or factory.' } )
db.definitions.insert( { word: 'anxious', definition: 'feeling or showing worry, nervousness, or unease about something with an uncertain outcome' } )
db.definitions.insert( { word: 'oval', definition: 'having a rounded and slightly elongated outline or shape like that of an egg' } )
db.definitions.insert( { word: 'spooky', definition: 'sinister or ghostly in a way that causes fear and unease' } )
db.definitions.insert( { word: 'wrap', definition: 'cover or enclose in paper or soft material' } )
db.definitions.insert( { word: 'pump', definition: 'a mechanical device using suction or pressure to raise or move liquids, compress gases, or force air into inflatable objects such as tyres' } )
db.definitions.insert( { word: 'divide', definition: 'separate or be separated into parts' } )
db.definitions.insert( { word: 'stew', definition: 'a dish of meat and vegetables cooked slowly in liquid in a closed dish or pan' } )
db.definitions.insert( { word: 'political', definition: 'relating to the government or public affairs of a country' } )
db.definitions.insert( { word: 'obese', definition: 'very fat or overweight' } )
db.definitions.insert( { word: 'brief', definition: 'of short duration; not lasting for long' } )
db.definitions.insert( { word: 'texture', definition: 'the feel, appearance, or consistency of a surface or substance' } )
db.definitions.insert( { word: 'thread', definition: 'a long, thin strand of cotton, nylon, or other fibres used in sewing or weaving' } )
db.definitions.insert( { word: 'spring', definition: 'move or jump suddenly or rapidly upwards or forwards' } )
db.definitions.insert( { word: 'sky', definition: 'the region of the atmosphere and outer space seen from the earth' } )
db.definitions.insert( { word: 'absorbing', definition: 'intensely interesting; engrossing' } )
db.definitions.insert( { word: 'risk', definition: 'a situation involving exposure to danger' } )
db.definitions.insert( { word: 'illustrious', definition: 'well known, respected, and admired for past achievements' } )
db.definitions.insert( { word: 'wave', definition: 'move one\'s hand to and fro in greeting or as a signal' } )
db.definitions.insert( { word: 'milk', definition: 'an opaque white fluid rich in fat and protein, secreted by female mammals for the nourishment of their young' } )
db.definitions.insert( { word: 'wholesale', definition: 'the business of selling of goods in large quantities and at low prices, typically to be sold on by retailers at a profit' } )
db.definitions.insert( { word: 'dare', definition: 'have the courage to do something' } )
db.definitions.insert( { word: 'long-term', definition: 'occurring over or relating to a long period of time' } )
db.definitions.insert( { word: 'desert', definition: 'abandon (a person, cause, or organization) in a way considered disloyal or treacherous' } )
db.definitions.insert( { word: 'frame', definition: 'a rigid structure that surrounds something such as a picture, door, or windowpane.' } )
db.definitions.insert( { word: 'roasted', definition: '(of food) cooked by prolonged exposure to heat in an oven or over a fire' } )
db.definitions.insert( { word: 'subsequent', definition: 'coming after something in time; following' } )
db.definitions.insert( { word: 'excited', definition: 'very enthusiastic and eager' } )
db.definitions.insert( { word: 'snake', definition: 'a long limbless reptile which has no eyelids, a short tail, and jaws that are capable of considerable extension. Some snakes have a venomous bite.' } )
db.definitions.insert( { word: 'song', definition: 'a short poem or other set of words set to music or meant to be sung' } )
db.definitions.insert( { word: 'need', definition: 'require (something) because it is essential or very important rather than just desirable' } )
db.definitions.insert( { word: 'ray', definition: 'each of the lines in which light (and heat) may seem to stream from the sun or any luminous body, or pass through a small opening' } )
db.definitions.insert( { word: 'north', definition: 'the direction in which a compass needle normally points, towards the horizon on the left-hand side of a person facing east, or the part of the horizon lying in this direction' } )
db.definitions.insert( { word: 'wanting', definition: 'lacking in a required or necessary quality' } )
db.definitions.insert( { word: 'fit', definition: 'of a suitable quality, standard, or type to meet the required purpose' } )
db.definitions.insert( { word: 'aback', definition: 'towards or situated to the rear; back' } )
db.definitions.insert( { word: 'cute', definition: 'attractive in a pretty or endearing way' } )
db.definitions.insert( { word: 'befitting', definition: 'appropriate to the occasion or purpose; suitable' } )
db.definitions.insert( { word: 'grotesque', definition: 'comically or repulsively ugly or distorted' } )
db.definitions.insert( { word: 'unwieldy', definition: '(of an object) difficult to move because of its size, shape, or weight' } )
db.definitions.insert( { word: 'impolite', definition: 'not having or showing good manners; rude' } )
db.definitions.insert( { word: 'callous', definition: 'showing or having an insensitive and cruel disregard for others' } )
db.definitions.insert( { word: 'handle', definition: 'feel or manipulate with the hands' } )
db.definitions.insert( { word: 'damage', definition: 'physical harm that impairs the value, usefulness, or normal function of something' } )
db.definitions.insert( { word: 'disgusted', definition: 'feeling or expressing revulsion or strong disapproval' } )
db.definitions.insert( { word: 'kettle', definition: 'a container or device in which water is boiled, having a lid, spout, and handle.' } )
db.definitions.insert( { word: 'sigh', definition: 'emit a long, deep audible breath expressing sadness, relief, tiredness, or similar' } )
db.definitions.insert( { word: 'explain', definition: 'make (an idea or situation) clear to someone by describing it in more detail or revealing relevant facts' } )
db.definitions.insert( { word: 'adorable', definition: 'inspiring great affection or delight' } )
db.definitions.insert( { word: 'thank', definition: 'express gratitude to (someone), especially by saying ‘Thank you’' } )
db.definitions.insert( { word: 'hand', definition: 'the end part of a person\'s arm beyond the wrist, including the palm, fingers, and thumb' } )
db.definitions.insert( { word: 'number', definition: 'an arithmetical value, expressed by a word, symbol, or figure, representing a particular quantity and used in counting and making calculations' } )
db.definitions.insert( { word: 'excite', definition: 'cause (someone) to feel very enthusiastic and eager' } )
db.definitions.insert( { word: 'enter', definition: 'come or go into (a place)' } )
db.definitions.insert( { word: 'tie', definition: 'attach or fasten with string or similar cord' } )
db.definitions.insert( { word: 'discovery', definition: 'the action or process of discovering or being discovered' } )
db.definitions.insert( { word: 'disapprove', definition: 'have or express an unfavourable opinion' } )
db.definitions.insert( { word: 'cloth', definition: 'woven or felted fabric made from wool, cotton, or a similar fibre' } )
db.definitions.insert( { word: 'ethereal', definition: 'extremely delicate and light in a way that seems not to be of this world' } )
db.definitions.insert( { word: 'ahead', definition: 'further forward in space; in the line of one\'s forward motion' } )
db.definitions.insert( { word: 'squeal', definition: 'a long, high-pitched cry or noise' } )
db.definitions.insert( { word: 'yoke', definition: 'a wooden crosspiece that is fastened over the necks of two animals and attached to the plough or cart that they are to pull.' } )
db.definitions.insert( { word: 'familiar', definition: 'well known from long or close association' } )
db.definitions.insert( { word: 'rich', definition: 'having a great deal of money or assets; wealthy' } )
db.definitions.insert( { word: 'royal', definition: 'having the status of a king or queen or a member of their family' } )
db.definitions.insert( { word: 'tiny', definition: 'very small' } )
db.definitions.insert( { word: 'peel', definition: 'remove the outer covering or skin from (a fruit or vegetable)' } )
db.definitions.insert( { word: 'brake', definition: 'a device for slowing or stopping a moving vehicle, typically by applying pressure to the wheels' } )
db.definitions.insert( { word: 'ablaze', definition: 'burning fiercely' } )
db.definitions.insert( { word: 'mighty', definition: 'possessing great and impressive power or strength, especially because of size' } )
db.definitions.insert( { word: 'play', definition: 'engage in activity for enjoyment and recreation rather than a serious or practical purpose' } )
db.definitions.insert( { word: 'nervous', definition: 'easily agitated or alarmed' } )
db.definitions.insert( { word: 'blood', definition: 'the red liquid that circulates in the arteries and veins of humans and other vertebrate animals, carrying oxygen to and carbon dioxide from the tissues of the body' } )
db.definitions.insert( { word: 'unbecoming', definition: '(especially of clothing or a colour) not flattering' } )
db.definitions.insert( { word: 'sharp', definition: '(of an object) having an edge or point that is able to cut or pierce something' } )
db.definitions.insert( { word: 'punch', definition: 'strike with the fist' } )
db.definitions.insert( { word: 'frighten', definition: 'make (someone) afraid or anxious' } )
db.definitions.insert( { word: 'melted', definition: 'having become liquefied by heating' } )
db.definitions.insert( { word: 'panicky', definition: 'feeling or characterized by uncontrollable fear or anxiety' } )
db.definitions.insert( { word: 'rare', definition: '(of an event, situation, or condition) not occurring very often' } )
db.definitions.insert( { word: 'dusty', definition: 'covered with, full of, or resembling dust' } )
db.definitions.insert( { word: 'nut', definition: 'a fruit consisting of a hard or tough shell around an edible kernel' } )
db.definitions.insert( { word: 'knee', definition: 'the joint between the thigh and the lower leg in humans' } )
db.definitions.insert( { word: 'burn', definition: '(of a fire) produce flames and heat while consuming a material such as coal or wood' } )
db.definitions.insert( { word: 'tramp', definition: 'walk heavily or noisily' } )
db.definitions.insert( { word: 'sleep', definition: 'a condition of body and mind that typically recurs for several hours every night, in which the eyes are closed, the postural muscles relaxed, the activity of the brain altered, and consciousness of the surroundings practically suspended' } )
db.definitions.insert( { word: 'earthy', definition: 'resembling or suggestive of earth or soil' } )
db.definitions.insert( { word: 'girl', definition: 'a female child' } )
db.definitions.insert( { word: 'lick', definition: 'pass the tongue over (something) in order to taste, moisten, or clean it' } )
db.definitions.insert( { word: 'connect', definition: 'bring together or into contact so that a real or notional link is established' } )
db.definitions.insert( { word: 'daily', definition: 'done, produced, or occurring every day or every weekday' } )
db.definitions.insert( { word: 'squeamish', definition: 'easily made to feel sick or disgusted' } )
db.definitions.insert( { word: 'love', definition: 'an intense feeling of deep affection' } )
db.definitions.insert( { word: 'spy', definition: 'a person employed by a government or other organization to secretly obtain information on an enemy or competitor.' } )
db.definitions.insert( { word: 'wandering', definition: 'travelling aimlessly from place to place; itinerant' } )
db.definitions.insert( { word: 'tender', definition: 'showing gentleness, kindness, and affection' } )
db.definitions.insert( { word: 'fertile', definition: '(of soil or land) producing or capable of producing abundant vegetation or crops' } )
db.definitions.insert( { word: 'lush', definition: '(of vegetation, especially grass) growing luxuriantly' } )
db.definitions.insert( { word: 'interest', definition: 'the feeling of wanting to know or learn about something or someone' } )
db.definitions.insert( { word: 'soda', definition: 'carbonated water (originally made with sodium bicarbonate) drunk alone or mixed with alcoholic drinks or fruit juice' } )
db.definitions.insert( { word: 'cowardly', definition: 'lacking courage' } )
db.definitions.insert( { word: 'stranger', definition: 'a person whom one does not know or with whom one is not familiar' } )
db.definitions.insert( { word: 'blade', definition: 'the flat cutting edge of a knife, saw, or other tool or weapon' } )
db.definitions.insert( { word: 'yawn', definition: 'involuntarily open one\'s mouth wide and inhale deeply due to tiredness or boredom' } )
db.definitions.insert( { word: 'polite', definition: 'having or showing behaviour that is respectful and considerate of other people' } )
db.definitions.insert( { word: 'attach', definition: 'join or fasten (something) to something else' } )
db.definitions.insert( { word: 'observe', definition: 'notice or perceive (something) and register it as being significant' } )
db.definitions.insert( { word: 'parsimonious', definition: 'very unwilling to spend money or use resources' } )
db.definitions.insert( { word: 'humorous', definition: 'causing laughter and amusement; comic' } )
db.definitions.insert( { word: 'tasteless', definition: 'lacking flavour' } )
db.definitions.insert( { word: 'mindless', definition: 'acting or done without justification and with no concern for the consequences' } )
db.definitions.insert( { word: 'optimal', definition: 'best or most favourable; optimum' } )
db.definitions.insert( { word: 'cobweb', definition: 'a spider\'s web, especially when old and dusty' } )
db.definitions.insert( { word: 'uneven', definition: 'not level or smooth' } )
db.definitions.insert( { word: 'fax', definition: 'an exact copy of a document made by electronic scanning and transmitted as data by telecommunications links' } )
db.definitions.insert( { word: 'healthy', definition: 'in a good physical or mental condition; in good health' } )
db.definitions.insert( { word: 'secretive', definition: '(of a person or an organization) inclined to conceal feelings and intentions or not to disclose information' } )
db.definitions.insert( { word: 'paper', definition: 'material manufactured in thin sheets from the pulp of wood or other fibrous substances, used for writing, drawing, or printing on, or as wrapping material' } )
db.definitions.insert( { word: 'strap', definition: 'a strip of leather, cloth, or other flexible material, used to fasten, secure, or carry something or to hold on to something' } )
db.definitions.insert( { word: 'detect', definition: 'discover or identify the presence or existence of' } )
db.definitions.insert( { word: 'equal', definition: 'being the same in quantity, size, degree, or value' } )
db.definitions.insert( { word: 'morning', definition: 'the period of time between midnight and noon, especially from sunrise to noon' } )
db.definitions.insert( { word: 'fearful', definition: 'feeling or showing fear or anxiety' } )
db.definitions.insert( { word: 'zebra', definition: 'an African wild horse with black-and-white stripes and an erect mane.' } )
db.definitions.insert( { word: 'glove', definition: 'a covering for the hand worn for protection against cold or dirt and typically having separate parts for each finger and the thumb' } )
db.definitions.insert( { word: 'post', definition: 'a long, sturdy piece of timber or metal set upright in the ground and used as a support or marker' } )
db.definitions.insert( { word: 'zonked', definition: 'under the influence of drugs or alcohol' } )
db.definitions.insert( { word: 'testy', definition: 'easily irritated; impatient and somewhat bad-tempered' } )
db.definitions.insert( { word: 'dime', definition: 'a ten-cent coin.' } )
db.definitions.insert( { word: 'jumpy', definition: '(of a person) anxious and uneasy' } )
db.definitions.insert( { word: 'overrated', definition: 'rated or valued too highly' } )
db.definitions.insert( { word: 'memory', definition: 'the faculty by which the mind stores and remembers information' } )
db.definitions.insert( { word: 'enjoy', definition: 'take delight or pleasure in (an activity or occasion)' } )
db.definitions.insert( { word: 'crack', definition: 'a line on the surface of something along which it has split without breaking apart' } )
db.definitions.insert( { word: 'innate', definition: 'inborn; natural' } )
db.definitions.insert( { word: 'taboo', definition: 'a social or religious custom prohibiting or restricting a particular practice or forbidding association with a particular person, place, or thing' } )
db.definitions.insert( { word: 'secretary', definition: 'a person employed by an individual or in an office to assist with correspondence, make appointments, and carry out administrative tasks' } )
db.definitions.insert( { word: 'carry', definition: 'support and move (someone or something) from one place to another' } )
db.definitions.insert( { word: 'happen', definition: 'take place; occur' } )
db.definitions.insert( { word: 'ear', definition: 'the organ of hearing and balance in humans and other vertebrates, especially the external part of this.' } )
db.definitions.insert( { word: 'hum', definition: 'make a low, steady continuous sound like that of a bee' } )
db.definitions.insert( { word: 'overwrought', definition: 'in a state of nervous excitement or anxiety' } )
db.definitions.insert( { word: 'condemned', definition: 'sentenced to a particular punishment, especially death' } )
db.definitions.insert( { word: 'decorate', definition: 'make (something) look more attractive by adding extra items or images to it' } )
db.definitions.insert( { word: 'paste', definition: 'a thick, soft, moist substance typically produced by mixing dry ingredients with a liquid' } )
db.definitions.insert( { word: 'welcome', definition: 'an instance or manner of greeting someone' } )
db.definitions.insert( { word: 'sock', definition: 'a garment for the foot and lower part of the leg, typically knitted from wool, cotton, or nylon.' } )
db.definitions.insert( { word: 'charge', definition: 'demand (an amount) as a price for a service rendered or goods supplied' } )
db.definitions.insert( { word: 'ball', definition: 'a solid or hollow spherical or egg-shaped object that is kicked, thrown, or hit in a game' } )
db.definitions.insert( { word: 'uncovered', definition: 'not covered' } )
db.definitions.insert( { word: 'pray', definition: 'address a prayer to God or another deity' } )
db.definitions.insert( { word: 'tawdry', definition: 'showy but cheap and of poor quality' } )
db.definitions.insert( { word: 'smoke', definition: 'a visible suspension of carbon or other particles in air, typically one emitted from a burning substance' } )
db.definitions.insert( { word: 'bubble', definition: 'a thin sphere of liquid enclosing air or another gas' } )
db.definitions.insert( { word: 'messy', definition: 'untidy or dirty' } )
db.definitions.insert( { word: 'actor', definition: 'a person whose profession is acting on the stage, in films, or on television.' } )
db.definitions.insert( { word: 'butter', definition: 'a pale yellow edible fatty substance made by churning cream and used as a spread or in cooking.' } )
db.definitions.insert( { word: 'kneel', definition: 'be in or assume a position in which the body is supported by a knee or the knees, as when praying or showing submission' } )
db.definitions.insert( { word: 'expert', definition: 'a person who is very knowledgeable about or skilful in a particular area' } )
db.definitions.insert( { word: 'skate', definition: 'an ice skate or roller skate' } )
db.definitions.insert( { word: 'call', definition: 'give (a baby or animal) a specified name' } )
db.definitions.insert( { word: 'coach', definition: 'a comfortably equipped single-decker bus used for longer journeys' } )
db.definitions.insert( { word: 'home', definition: 'the place where one lives permanently, especially as a member of a family or household' } )
db.definitions.insert( { word: 'sincere', definition: 'free from pretence or deceit; proceeding from genuine feelings' } )
db.definitions.insert( { word: 'settle', definition: 'resolve or reach an agreement about (an argument or problem)' } )
db.definitions.insert( { word: 'murder', definition: 'the unlawful premeditated killing of one human being by another' } )
db.definitions.insert( { word: 'habitual', definition: 'done constantly or as a habit' } )
db.definitions.insert( { word: 'smash', definition: 'violently break (something) into pieces' } )
db.definitions.insert( { word: 'bloody', definition: 'covered, smeared, or running with blood' } )
db.definitions.insert( { word: 'maid', definition: 'a female domestic servant' } )
db.definitions.insert( { word: 'filthy', definition: 'disgustingly dirty' } )
db.definitions.insert( { word: 'coat', definition: 'an outer garment with sleeves, worn outdoors and typically extending below the hips' } )
db.definitions.insert( { word: 'price', definition: 'the amount of money expected, required, or given in payment for something' } )
db.definitions.insert( { word: 'minister', definition: '(in certain countries) a head of a government department' } )
db.definitions.insert( { word: 'curve', definition: 'a line or outline which gradually deviates from being straight for some or all of its length' } )
db.definitions.insert( { word: 'thirsty', definition: 'feeling a need to drink something' } )
db.definitions.insert( { word: 'ripe', definition: '(of fruit or grain) developed to the point of readiness for harvesting and eating' } )
db.definitions.insert( { word: 'page', definition: 'one or both sides of a sheet of paper in a book, magazine, newspaper, or other collection of bound sheets' } )
db.definitions.insert( { word: 'accurate', definition: '(especially of information, measurements, or predictions) correct in all details; exact' } )
db.definitions.insert( { word: 'share', definition: 'a part or portion of a larger amount which is divided among a number of people, or to which a number of people contribute' } )
db.definitions.insert( { word: 'homely', definition: '(of a place or surroundings) simple but cosy and comfortable, as in one\'s own home' } )
db.definitions.insert( { word: 'nondescript', definition: 'lacking distinctive or interesting features or characteristics' } )
db.definitions.insert( { word: 'teaching', definition: 'the occupation, profession, or work of a teacher' } )
db.definitions.insert( { word: 'helpful', definition: 'giving or ready to give help' } )
db.definitions.insert( { word: 'pause', definition: 'interrupt action or speech briefly' } )
db.definitions.insert( { word: 'swanky', definition: 'stylishly luxurious and expensive' } )
db.definitions.insert( { word: 'cause', definition: 'a person or thing that gives rise to an action, phenomenon, or condition' } )
db.definitions.insert( { word: 'train', definition: 'teach (a person or animal) a particular skill or type of behaviour through practice and instruction over a period of time' } )
db.definitions.insert( { word: 'compare', definition: 'estimate, measure, or note the similarity or dissimilarity between' } )
db.definitions.insert( { word: 'gaze', definition: 'look steadily and intently, especially in admiration, surprise, or thought' } )
db.definitions.insert( { word: 'signal', definition: 'a gesture, action, or sound that is used to convey information or instructions, typically by prearrangement between the parties concerned' } )
db.definitions.insert( { word: 'achiever', definition: 'a person who achieves a high or specified level of success' } )
db.definitions.insert( { word: 'woozy', definition: 'unsteady, dizzy, or dazed' } )
db.definitions.insert( { word: 'salty', definition: 'tasting of, containing, or preserved with salt' } )
db.definitions.insert( { word: 'volleyball', definition: 'a game for two teams, usually of six players, in which a large ball is hit by hand over a high net, the aim being to score points by making the ball reach the ground on the opponent\'s side of the court.' } )
db.definitions.insert( { word: 'black', definition: 'of the very darkest colour owing to the absence of or complete absorption of light; the opposite of white' } )
db.definitions.insert( { word: 'ultra', definition: 'an extremist' } )
db.definitions.insert( { word: 'rotten', definition: 'suffering from decay' } )
db.definitions.insert( { word: 'trick', definition: 'a cunning act or scheme intended to deceive or outwit someone' } )
db.definitions.insert( { word: 'lewd', definition: 'crude and offensive in a sexual way' } )
db.definitions.insert( { word: 'place', definition: 'a particular position, point, or area in space; a location' } )
db.definitions.insert( { word: 'profuse', definition: '(especially of something offered or discharged) very plentiful; abundant' } )
db.definitions.insert( { word: 'railway', definition: 'a track made of steel rails along which trains run.' } )
db.definitions.insert( { word: 'hellish', definition: 'of or like hell' } )
db.definitions.insert( { word: 'giant', definition: 'an imaginary or mythical being of human form but superhuman size.' } )
db.definitions.insert( { word: 'mourn', definition: 'feel or show sorrow for the death of (someone), typically by following conventions such as the wearing of black clothes' } )
db.definitions.insert( { word: 'shrug', definition: 'raise (one\'s shoulders) slightly and momentarily to express doubt, ignorance, or indifference' } )
db.definitions.insert( { word: 'instrument', definition: 'a tool or implement, especially one for precision work' } )
db.definitions.insert( { word: 'prefer', definition: 'like (one thing or person) better than another or others; tend to choose' } )
db.definitions.insert( { word: 'fretful', definition: 'feeling or expressing distress or irritation' } )
db.definitions.insert( { word: 'petite', definition: 'attractively small and dainty (used of a woman)' } )
db.definitions.insert( { word: 'stomach', definition: 'the internal organ in which the major part of the digestion of food occurs, being (in humans and many mammals) a pear-shaped enlargement of the alimentary canal linking the oesophagus to the small intestine' } )
db.definitions.insert( { word: 'stroke', definition: 'an act of hitting or striking someone or something; a blow' } )
db.definitions.insert( { word: 'overjoyed', definition: 'extremely happy' } )
db.definitions.insert( { word: 'son', definition: 'a boy or man in relation to either or both of his parents.' } )
db.definitions.insert( { word: 'fancy', definition: 'elaborate in structure or decoration' } )
db.definitions.insert( { word: 'freezing', definition: 'below 0°C' } )
db.definitions.insert( { word: 'historical', definition: 'of or concerning history or past events' } )
db.definitions.insert( { word: 'productive', definition: 'producing or able to produce large amounts of goods, crops, or other commodities' } )
db.definitions.insert( { word: 'righteous', definition: 'morally right or justifiable' } )
db.definitions.insert( { word: 'placid', definition: 'not easily upset or excited' } )
db.definitions.insert( { word: 'sticky', definition: 'tending or designed to stick to things on contact' } )
db.definitions.insert( { word: 'outrageous', definition: 'shockingly bad or excessive' } )
db.definitions.insert( { word: 'hill', definition: 'a naturally raised area of land, not as high or craggy as a mountain.' } )
db.definitions.insert( { word: 'chew', definition: 'bite and work (food) in the mouth with the teeth, especially to make it easier to swallow' } )
db.definitions.insert( { word: 'voracious', definition: 'wanting or devouring great quantities of food' } )
db.definitions.insert( { word: 'school', definition: 'an institution for educating children' } )
db.definitions.insert( { word: 'summer', definition: 'the warmest season of the year, in the northern hemisphere from June to August and in the southern hemisphere from December to February' } )
db.definitions.insert( { word: 'astonishing', definition: 'extremely surprising or impressive; amazing' } )
db.definitions.insert( { word: 'well-to-do', definition: 'wealthy; prosperous' } )
db.definitions.insert( { word: 'strange', definition: 'unusual or surprising; difficult to understand or explain' } )
db.definitions.insert( { word: 'bruise', definition: 'an injury appearing as an area of discoloured skin on the body, caused by a blow or impact rupturing underlying blood vessels' } )
db.definitions.insert( { word: 'dad', definition: 'one\'s father' } )
db.definitions.insert( { word: 'drink', definition: 'take (a liquid) into the mouth and swallow' } )
db.definitions.insert( { word: 'club', definition: 'an association dedicated to a particular interest or activity' } )
db.definitions.insert( { word: 'ad hoc', definition: 'when necessary or needed' } )
db.definitions.insert( { word: 'crate', definition: 'a slatted wooden case used for transporting goods' } )
db.definitions.insert( { word: 'yak', definition: 'a large domesticated wild ox with shaggy hair, humped shoulders, and large horns, used in Tibet as a pack animal and for its milk, meat, and hide.' } )
db.definitions.insert( { word: 'bless', definition: 'pronounce words in a religious rite in order to confer or invoke divine favour upon; ask God to look favourably on' } )
db.definitions.insert( { word: 'muddle', definition: 'bring into a disordered or confusing state' } )
db.definitions.insert( { word: 'curious', definition: 'eager to know or learn something' } )
db.definitions.insert( { word: 'occur', definition: 'happen; take place' } )
db.definitions.insert( { word: 'vegetable', definition: 'a plant or part of a plant used as food, such as a cabbage, potato, turnip, or bean' } )
db.definitions.insert( { word: 'itch', definition: 'an uncomfortable sensation on the skin that causes a desire to scratch.' } )
db.definitions.insert( { word: 'toothsome', definition: '(of food) temptingly tasty' } )
db.definitions.insert( { word: 'committee', definition: 'a group of people appointed for a specific function by a larger group and typically consisting of members of that group' } )
db.definitions.insert( { word: 'cure', definition: 'relieve (a person or animal) of the symptoms of a disease or condition' } )
db.definitions.insert( { word: 'frantic', definition: 'distraught with fear, anxiety, or other emotion' } )
db.definitions.insert( { word: 'design', definition: 'a plan or drawing produced to show the look and function or workings of a building, garment, or other object before it is made' } )
db.definitions.insert( { word: 'fence', definition: 'a barrier, railing, or other upright structure, typically of wood or wire, enclosing an area of ground to prevent or control access or escape.' } )
db.definitions.insert( { word: 'mute', definition: 'refraining from speech or temporarily speechless' } )
db.definitions.insert( { word: 'gigantic', definition: 'of very great size or extent; huge or enormous' } )
db.definitions.insert( { word: 'impress', definition: 'make (someone) feel admiration and respect' } )
db.definitions.insert( { word: 'nippy', definition: 'able to move quickly; nimble' } )
db.definitions.insert( { word: 'egg', definition: 'an oval or round object laid by a female bird, reptile, fish, or invertebrate, usually containing a developing embryo. The eggs of birds are enclosed in a chalky shell, while those of reptiles are in a leathery membrane.' } )
db.definitions.insert( { word: 'capricious', definition: 'given to sudden and unaccountable changes of mood or behaviour' } )
db.definitions.insert( { word: 'spare', definition: 'additional to what is required for ordinary use' } )
db.definitions.insert( { word: 'account', definition: 'a report or description of an event or experience' } )
db.definitions.insert( { word: 'ludicrous', definition: 'so foolish, unreasonable, or out of place as to be amusing' } )
db.definitions.insert( { word: 'fallacious', definition: 'based on a mistaken belief' } )
db.definitions.insert( { word: 'treat', definition: 'behave towards or deal with in a certain way' } )
db.definitions.insert( { word: 'prose', definition: 'written or spoken language in its ordinary form, without metrical structure' } )
db.definitions.insert( { word: 'wreck', definition: 'the destruction of a ship at sea; a shipwreck' } )
db.definitions.insert( { word: 'acrid', definition: 'unpleasantly bitter or pungent' } )
db.definitions.insert( { word: 'donkey', definition: 'a domesticated hoofed mammal of the horse family with long ears and a braying call, used as a beast of burden; an ass.' } )
db.definitions.insert( { word: 'awful', definition: 'very bad or unpleasant' } )
db.definitions.insert( { word: 'zip', definition: 'fasten with a zip' } )
db.definitions.insert( { word: 'concern', definition: 'relate to; be about' } )
db.definitions.insert( { word: 'holiday', definition: 'an extended period of leisure and recreation, especially one spent away from home or in travelling.' } )
db.definitions.insert( { word: 'punish', definition: 'inflict a penalty or sanction on (someone) as retribution for an offence, especially a transgression of a legal or moral code' } )
db.definitions.insert( { word: 'motionless', definition: 'not moving; stationary' } )
db.definitions.insert( { word: 'hover', definition: 'remain in one place in the air' } )
db.definitions.insert( { word: 'gorgeous', definition: 'beautiful; very attractive' } )
db.definitions.insert( { word: 'property', definition: 'a thing or things belonging to someone; possessions collectively' } )
db.definitions.insert( { word: 'noise', definition: 'a sound, especially one that is loud or unpleasant or that causes disturbance' } )
db.definitions.insert( { word: 'roomy', definition: '(especially of accommodation) having plenty of room; spacious' } )
db.definitions.insert( { word: 'warlike', definition: 'disposed towards or threatening war; hostile' } )
db.definitions.insert( { word: 'tenuous', definition: 'very weak or slight' } )
db.definitions.insert( { word: 'diligent', definition: 'having or showing care and conscientiousness in one\'s work or duties' } )
db.definitions.insert( { word: 'steel', definition: 'a hard, strong grey or bluish-grey alloy of iron with carbon and usually other elements, used as a structural and fabricating material' } )
db.definitions.insert( { word: 'woebegone', definition: 'sad or miserable in appearance' } )
db.definitions.insert( { word: 'clap', definition: 'strike the palms of (one\'s hands) together repeatedly, typically in order to applaud someone or something' } )
db.definitions.insert( { word: 'report', definition: 'give a spoken or written account of something that one has observed, heard, done, or investigated' } )
db.definitions.insert( { word: 'tree', definition: 'a woody perennial plant, typically having a single stem or trunk growing to a considerable height and bearing lateral branches at some distance from the ground' } )
db.definitions.insert( { word: 'flagrant', definition: '(of an action considered wrong or immoral) conspicuously or obviously offensive' } )
db.definitions.insert( { word: 'mouth', definition: 'the opening and cavity in the lower part of the human face, surrounded by the lips, through which food is taken in and vocal sounds are emitted' } )
db.definitions.insert( { word: 'base', definition: 'the lowest part or edge of something, especially the part on which it rests or is supported' } )
db.definitions.insert( { word: 'ready', definition: 'in a suitable state for an action or situation; fully prepared' } )
db.definitions.insert( { word: 'flame', definition: 'a hot glowing body of ignited gas that is generated by something on fire' } )
db.definitions.insert( { word: 'plain', definition: 'not decorated or elaborate; simple or basic in character' } )
db.definitions.insert( { word: 'futuristic', definition: 'having or involving very modern technology or design' } )
db.definitions.insert( { word: 'own', definition: 'used with a possessive to emphasize that someone or something belongs or relates to the person or thing mentioned' } )
db.definitions.insert( { word: 'rake', definition: 'an implement consisting of a pole with a toothed crossbar or fine tines at the end, used especially for drawing together cut grass or smoothing loose soil or gravel.' } )
db.definitions.insert( { word: 'medical', definition: 'relating to the science or practice of medicine' } )
db.definitions.insert( { word: 'empty', definition: 'containing nothing; not filled or occupied' } )
db.definitions.insert( { word: 'uptight', definition: 'anxious or angry in a tense and overly controlled way' } )
db.definitions.insert( { word: 'pointless', definition: 'having little or no sense, use, or purpose' } )
db.definitions.insert( { word: 'stimulating', definition: 'encouraging or arousing interest or enthusiasm' } )
db.definitions.insert( { word: 'secret', definition: 'not known or seen or not meant to be known or seen by others' } )
db.definitions.insert( { word: 'disastrous', definition: 'causing great damage' } )
db.definitions.insert( { word: 'minute', definition: 'a period of time equal to sixty seconds or a sixtieth of an hour' } )
db.definitions.insert( { word: 'unarmed', definition: 'not equipped with or carrying weapons' } )
db.definitions.insert( { word: 'momentous', definition: 'of great importance or significance, especially in having a bearing on future events' } )
db.definitions.insert( { word: 'female', definition: 'of or denoting the sex that can bear offspring or produce eggs, distinguished biologically by the production of gametes (ova) which can be fertilized by male gametes' } )
db.definitions.insert( { word: 'frail', definition: '(of a person) weak and delicate' } )
db.definitions.insert( { word: 'oven', definition: 'an enclosed compartment, usually part of a cooker, for cooking and heating food' } )
db.definitions.insert( { word: 'grease', definition: 'a thick oily substance, especially as used as a lubricant' } )
db.definitions.insert( { word: 'jar', definition: 'a wide-mouthed cylindrical container made of glass or pottery and typically having a lid, used especially for storing food' } )
db.definitions.insert( { word: 'harsh', definition: 'unpleasantly rough or jarring to the senses' } )
db.definitions.insert( { word: 'rat', definition: 'a rodent that resembles a large mouse, typically having a pointed snout and a long tail. Some kinds have become cosmopolitan and are sometimes responsible for transmitting diseases.' } )
db.definitions.insert( { word: 'used', definition: 'having already been used' } )
db.definitions.insert( { word: 'evasive', definition: 'tending to avoid commitment or self-revelation, especially by responding only indirectly' } )
db.definitions.insert( { word: 'basin', definition: 'a bowl for washing, typically attached to a wall and having taps connected to a water supply; a washbasin.' } )
db.definitions.insert( { word: 'adjustment', definition: 'a small alteration or movement made to achieve a desired fit, appearance, or result' } )
db.definitions.insert( { word: 'wiry', definition: 'resembling wire in form and texture' } )
db.definitions.insert( { word: 'fuzzy', definition: 'having a frizzy texture or appearance' } )
db.definitions.insert( { word: 'delay', definition: 'make (someone or something) late or slow' } )
db.definitions.insert( { word: 'face', definition: 'the front part of a person\'s head from the forehead to the chin, or the corresponding part in an animal' } )
db.definitions.insert( { word: 'march', definition: 'walk in a military manner with a regular measured tread' } )
db.definitions.insert( { word: 'scene', definition: 'the place where an incident in real life or fiction occurs or occurred' } )
db.definitions.insert( { word: 'acceptable', definition: 'able to be agreed on; suitable' } )
db.definitions.insert( { word: 'suggestion', definition: 'an idea or plan put forward for consideration' } )
db.definitions.insert( { word: 'colossal', definition: 'extremely large or great' } )
db.definitions.insert( { word: 'abounding', definition: 'very plentiful; abundant' } )
db.definitions.insert( { word: 'mist', definition: 'a cloud of tiny water droplets suspended in the atmosphere at or near the earth\'s surface that limits visibility (to a lesser extent than fog; strictly, with visibility remaining above 1 km (1,100 yards))' } )
db.definitions.insert( { word: 'scrub', definition: 'rub (someone or something) hard so as to clean them, typically with a brush and water' } )
db.definitions.insert( { word: 'violet', definition: 'a herbaceous plant of temperate regions, typically having purple, blue, or white five-petalled flowers, one petal of which forms a landing pad for pollinating insects.' } )
db.definitions.insert( { word: 'imminent', definition: 'about to happen' } )
db.definitions.insert( { word: 'rough', definition: 'having an uneven or irregular surface; not smooth or level' } )
db.definitions.insert( { word: 'different', definition: 'not the same as another or each other; unlike in nature, form, or quality' } )
db.definitions.insert( { word: 'aware', definition: 'having knowledge or perception of a situation or fact' } )
