/* This file was generated by the Hex-Rays decompiler.
   Copyright (c) 2007-2020 Hex-Rays <info@hex-rays.com>

   Detected compiler: GNU C++
*/

#include <defs.h>


//-------------------------------------------------------------------------
// Function declarations

__int64 (**init_proc())(void);
void sub_1020();
// void setbuf(FILE *stream, char *buf);
// int putc(int c, FILE *stream);
// int __fastcall _cxa_finalize(void *);
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void));
FILE **deregister_tm_clones();
__int64 __fastcall register_tm_clones(); // weak
FILE **_do_global_dtors_aux();
__int64 __fastcall frame_dummy(_QWORD, _QWORD, _QWORD); // weak
__int64 __fastcall c16(); // weak
__int64 c32();
__int64 c19();
__int64 c22();
__int64 c15(void); // weak
__int64 c36(void); // weak
__int64 c0(void); // weak
__int64 c35(void); // weak
__int64 c25(void); // weak
__int64 c14(void); // weak
__int64 c4(void); // weak
__int64 c13(void); // weak
__int64 c10(void); // weak
__int64 c28(void); // weak
__int64 c2(void); // weak
__int64 c29(void); // weak
__int64 c21(void); // weak
__int64 c12(void); // weak
__int64 c34(void); // weak
__int64 c17();
__int64 c30(void); // weak
__int64 __fastcall c18(); // weak
__int64 __fastcall c23(); // weak
__int64 __fastcall c37(); // weak
__int64 __fastcall c1(); // weak
__int64 __fastcall c7(); // weak
__int64 __fastcall c26(); // weak
__int64 __fastcall c11(); // weak
__int64 __fastcall c33(); // weak
__int64 __fastcall c24(); // weak
__int64 __fastcall c5(); // weak
__int64 __fastcall c27(); // weak
__int64 __fastcall c3(); // weak
__int64 __fastcall c38(); // weak
__int64 __fastcall c8(); // weak
__int64 __fastcall c31(); // weak
__int64 __fastcall c6(); // weak
__int64 __fastcall c20(); // weak
__int64 __fastcall c39(); // weak
__int64 __fastcall c9(); // weak
int __cdecl main(int argc, const char **argv, const char **envp);
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3);
void _libc_csu_fini(void); // idb
void term_proc();
// int __fastcall _libc_start_main(int (__fastcall *main)(int, char **, char **), int argc, char **ubp_av, void (*init)(void), void (*fini)(void), void (*rtld_fini)(void), void *stack_end);
// int __fastcall __cxa_finalize(void *);
// __int64 _gmon_start__(void); weak

//-------------------------------------------------------------------------
// Data declarations

__int64 (__fastcall *_frame_dummy_init_array_entry)() = &frame_dummy; // weak
__int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)() = &_do_global_dtors_aux; // weak
void *_dso_handle = &_dso_handle; // idb
char flag[320] =
{
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  'j',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  'b',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  'o',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  'o',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\x88',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '<',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\b',
  '\xF2',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\x02',
  '\xBA',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  'L',
  '\xD3',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\x19',
  '\xCC',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\x02',
  '\xB3',
  '\x8B',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\xE6',
  '\xC0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\x18',
  'S',
  '\xBF',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\b',
  '\x1B',
  '\x94',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  '\xDA',
  '\xF2',
  '\x19',
  '\0',
  '\0',
  '\0',
  '\0',
  '\0',
  'H',
  '\xFB',
  '\n',
  '\0',
  '\0',
  '\0',
  '\0',
  '\a',
  '\xB2',
  '\x85',
  '\xB3',
  '\0',
  '\0',
  '\0',
  '\0',
  '\x02',
  '\x90',
  '\xD7',
  '3',
  '\0',
  '\0',
  '\0',
  '\0',
  'E',
  'F',
  '\xB3',
  '\xEB',
  '\0',
  '\0',
  '\0',
  '\0',
  '\x17',
  '\x17',
  '\x91',
  '/',
  '\0',
  '\0',
  '\0',
  '\x02',
  'o',
  '|',
  'R',
  '\xD7',
  '\0',
  '\0',
  '\0',
  '\0',
  '\xCF',
  '\xD4',
  '\x1B',
  '\xB0',
  '\0',
  '\0',
  '\0',
  '\x15',
  '\xEB',
  '^',
  '\xE8',
  '/',
  '\0',
  '\0',
  '\0',
  '\a',
  'N',
  't',
  '\xF8',
  'w',
  '\0',
  '\0',
  '\0',
  '\xC5',
  'F',
  'V',
  '*',
  '\xD7',
  '\0',
  '\0',
  '\0',
  'A',
  '\xC2',
  '\x1C',
  '\xB8',
  '\x8D',
  '\0',
  '\0',
  '\x06',
  '\xEF',
  'y',
  '\a',
  '\x7F',
  '\x9A',
  '\0',
  '\0',
  '\x02',
  'O',
  '\xD3',
  '\x02',
  '\x7F',
  '\x82',
  '\0',
  '\0',
  '>',
  'k',
  'A',
  'C',
  '}',
  '\xF6',
  '\0',
  '\0',
  '\x14',
  '\xCE',
  'k',
  '\x16',
  '\x7F',
  '\\',
  '\0',
  '\x02',
  '1',
  '\xC5',
  'K',
  '_',
  'j',
  '\x18',
  '\0',
  '\0',
  '\xBB',
  'A',
  '\xC3',
  '\xCA',
  'x',
  '\xDB',
  '\0',
  '\x13',
  '\xBF',
  '\xEF',
  '\xA6',
  'Z',
  '\xBB',
  '\xF6',
  '\0',
  '\x06',
  '\x95',
  'O',
  '\xE2',
  '\x1E',
  '>',
  '\xF5',
  '\0',
  '\xB1',
  '\xBF',
  'l',
  '\xD9',
  '0',
  '\x97',
  '\xF2',
  '\0',
  ';',
  '?',
  '\xCE',
  '\xF3',
  '\x10',
  '2',
  '\xED',
  '\x06',
  '?',
  '\xBA',
  '\xD3',
  '\xA2',
  '\xB5',
  'T',
  '\x18',
  '\x02',
  '\x15',
  '>',
  'F',
  '\x8B',
  '\x91',
  '\xC6',
  '\xA8',
  '8',
  '=',
  '\x91',
  'p',
  '\xB8',
  '_',
  '\xF8',
  'u',
  '\x12',
  '\xBF',
  '0',
  'z',
  '\xE8',
  '\x1F',
  '\xFD',
  '$'
}; // idb
__int64 (__fastcall *off_41A0)() = &c32; // weak
FILE *_bss_start; // idb
char completed_0; // weak


//----- (0000000000001000) ----------------------------------------------------
__int64 (**init_proc())(void)
{
  __int64 (**result)(void); // rax

  result = &_gmon_start__;
  if ( &_gmon_start__ )
    result = (__int64 (**)(void))_gmon_start__();
  return result;
}
// 4320: using guessed type __int64 _gmon_start__(void);

//----- (0000000000001020) ----------------------------------------------------
void sub_1020()
{
  JUMPOUT(0LL);
}
// 1026: control flows out of bounds to 0

//----- (0000000000001060) ----------------------------------------------------
// positive sp value has been detected, the output may be wrong!
void __fastcall __noreturn start(__int64 a1, __int64 a2, void (*a3)(void))
{
  __int64 v3; // rax
  int v4; // esi
  __int64 v5; // [rsp-8h] [rbp-8h] BYREF
  char *retaddr; // [rsp+0h] [rbp+0h] BYREF

  v4 = v5;
  v5 = v3;
  _libc_start_main(
    (int (__fastcall *)(int, char **, char **))main,
    v4,
    &retaddr,
    (void (*)(void))_libc_csu_init,
    _libc_csu_fini,
    a3,
    &v5);
  __halt();
}
// 1066: positive sp value 8 has been found
// 106D: variable 'v3' is possibly undefined

//----- (0000000000001090) ----------------------------------------------------
FILE **deregister_tm_clones()
{
  return &_bss_start;
}

//----- (00000000000010C0) ----------------------------------------------------
__int64 register_tm_clones()
{
  return 0LL;
}
// 10C0: using guessed type __int64 __fastcall register_tm_clones();

//----- (0000000000001100) ----------------------------------------------------
FILE **_do_global_dtors_aux()
{
  FILE **result; // rax

  if ( !completed_0 )
  {
    if ( &__cxa_finalize )
      _cxa_finalize(_dso_handle);
    result = deregister_tm_clones();
    completed_0 = 1;
  }
  return result;
}
// 42E8: using guessed type char completed_0;

//----- (0000000000001145) ----------------------------------------------------
__int64 c16()
{
  return 1LL;
}
// 1145: using guessed type __int64 __fastcall c16();

//----- (0000000000001150) ----------------------------------------------------
__int64 c32()
{
  return 3LL;
}

//----- (000000000000115B) ----------------------------------------------------
__int64 c19()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c32(); ++i )
    v2 += c32();
  return v2;
}

//----- (000000000000119E) ----------------------------------------------------
__int64 c22()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c19(); ++i )
    v2 += c32();
  return v2;
}

//----- (00000000000011E1) ----------------------------------------------------
__int64 c15()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c19(); ++i )
    v2 += c19();
  return v2;
}
// 11E1: using guessed type __int64 __fastcall c15();

//----- (0000000000001224) ----------------------------------------------------
__int64 c36()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c22(); ++i )
    v2 += c19();
  return v2;
}
// 1224: using guessed type __int64 __fastcall c36();

//----- (0000000000001267) ----------------------------------------------------
__int64 c0()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c22(); ++i )
    v2 += c22();
  return v2;
}
// 1267: using guessed type __int64 __fastcall c0();

//----- (00000000000012AA) ----------------------------------------------------
__int64 c35()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c15(); ++i )
    v2 += c22();
  return v2;
}
// 11E1: using guessed type __int64 c15(void);
// 12AA: using guessed type __int64 __fastcall c35();

//----- (00000000000012ED) ----------------------------------------------------
__int64 c25()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c15(); ++i )
    v2 += c15();
  return v2;
}
// 11E1: using guessed type __int64 c15(void);
// 12ED: using guessed type __int64 __fastcall c25();

//----- (0000000000001330) ----------------------------------------------------
__int64 c14()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c36(); ++i )
    v2 += c15();
  return v2;
}
// 11E1: using guessed type __int64 c15(void);
// 1224: using guessed type __int64 c36(void);
// 1330: using guessed type __int64 __fastcall c14();

//----- (0000000000001373) ----------------------------------------------------
__int64 c4()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c36(); ++i )
    v2 += c36();
  return v2;
}
// 1224: using guessed type __int64 c36(void);
// 1373: using guessed type __int64 __fastcall c4();

//----- (00000000000013B6) ----------------------------------------------------
__int64 c13()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c0(); ++i )
    v2 += c36();
  return v2;
}
// 1224: using guessed type __int64 c36(void);
// 1267: using guessed type __int64 c0(void);
// 13B6: using guessed type __int64 __fastcall c13();

//----- (00000000000013F9) ----------------------------------------------------
__int64 c10()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c0(); ++i )
    v2 += c0();
  return v2;
}
// 1267: using guessed type __int64 c0(void);
// 13F9: using guessed type __int64 __fastcall c10();

//----- (000000000000143C) ----------------------------------------------------
__int64 c28()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c35(); ++i )
    v2 += c0();
  return v2;
}
// 1267: using guessed type __int64 c0(void);
// 12AA: using guessed type __int64 c35(void);
// 143C: using guessed type __int64 __fastcall c28();

//----- (000000000000147F) ----------------------------------------------------
__int64 c2()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c35(); ++i )
    v2 += c35();
  return v2;
}
// 12AA: using guessed type __int64 c35(void);
// 147F: using guessed type __int64 __fastcall c2();

//----- (00000000000014C2) ----------------------------------------------------
__int64 c29()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c25(); ++i )
    v2 += c35();
  return v2;
}
// 12AA: using guessed type __int64 c35(void);
// 12ED: using guessed type __int64 c25(void);
// 14C2: using guessed type __int64 __fastcall c29();

//----- (0000000000001505) ----------------------------------------------------
__int64 c21()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c25(); ++i )
    v2 += c25();
  return v2;
}
// 12ED: using guessed type __int64 c25(void);
// 1505: using guessed type __int64 __fastcall c21();

//----- (0000000000001548) ----------------------------------------------------
__int64 c12()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c14(); ++i )
    v2 += c25();
  return v2;
}
// 12ED: using guessed type __int64 c25(void);
// 1330: using guessed type __int64 c14(void);
// 1548: using guessed type __int64 __fastcall c12();

//----- (000000000000158B) ----------------------------------------------------
__int64 c34()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c14(); ++i )
    v2 += c14();
  return v2;
}
// 1330: using guessed type __int64 c14(void);
// 158B: using guessed type __int64 __fastcall c34();

//----- (00000000000015CE) ----------------------------------------------------
__int64 c17()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c4(); ++i )
    v2 += c14();
  return v2;
}
// 1330: using guessed type __int64 c14(void);
// 1373: using guessed type __int64 c4(void);

//----- (0000000000001611) ----------------------------------------------------
__int64 c30()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c4(); ++i )
    v2 += c4();
  return v2;
}
// 1373: using guessed type __int64 c4(void);
// 1611: using guessed type __int64 __fastcall c30();

//----- (0000000000001654) ----------------------------------------------------
__int64 c18()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c13(); ++i )
    v2 += c4();
  return v2;
}
// 1373: using guessed type __int64 c4(void);
// 13B6: using guessed type __int64 c13(void);
// 1654: using guessed type __int64 __fastcall c18();

//----- (0000000000001697) ----------------------------------------------------
__int64 c23()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c13(); ++i )
    v2 += c13();
  return v2;
}
// 13B6: using guessed type __int64 c13(void);
// 1697: using guessed type __int64 __fastcall c23();

//----- (00000000000016DA) ----------------------------------------------------
__int64 c37()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c10(); ++i )
    v2 += c13();
  return v2;
}
// 13B6: using guessed type __int64 c13(void);
// 13F9: using guessed type __int64 c10(void);
// 16DA: using guessed type __int64 __fastcall c37();

//----- (000000000000171D) ----------------------------------------------------
__int64 c1()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c10(); ++i )
    v2 += c10();
  return v2;
}
// 13F9: using guessed type __int64 c10(void);
// 171D: using guessed type __int64 __fastcall c1();

//----- (0000000000001760) ----------------------------------------------------
__int64 c7()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c28(); ++i )
    v2 += c10();
  return v2;
}
// 13F9: using guessed type __int64 c10(void);
// 143C: using guessed type __int64 c28(void);
// 1760: using guessed type __int64 __fastcall c7();

//----- (00000000000017A3) ----------------------------------------------------
__int64 c26()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c28(); ++i )
    v2 += c28();
  return v2;
}
// 143C: using guessed type __int64 c28(void);
// 17A3: using guessed type __int64 __fastcall c26();

//----- (00000000000017E6) ----------------------------------------------------
__int64 c11()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c2(); ++i )
    v2 += c28();
  return v2;
}
// 143C: using guessed type __int64 c28(void);
// 147F: using guessed type __int64 c2(void);
// 17E6: using guessed type __int64 __fastcall c11();

//----- (0000000000001829) ----------------------------------------------------
__int64 c33()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c2(); ++i )
    v2 += c2();
  return v2;
}
// 147F: using guessed type __int64 c2(void);
// 1829: using guessed type __int64 __fastcall c33();

//----- (000000000000186C) ----------------------------------------------------
__int64 c24()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c29(); ++i )
    v2 += c2();
  return v2;
}
// 147F: using guessed type __int64 c2(void);
// 14C2: using guessed type __int64 c29(void);
// 186C: using guessed type __int64 __fastcall c24();

//----- (00000000000018AF) ----------------------------------------------------
__int64 c5()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c29(); ++i )
    v2 += c29();
  return v2;
}
// 14C2: using guessed type __int64 c29(void);
// 18AF: using guessed type __int64 __fastcall c5();

//----- (00000000000018F2) ----------------------------------------------------
__int64 c27()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c21(); ++i )
    v2 += c29();
  return v2;
}
// 14C2: using guessed type __int64 c29(void);
// 1505: using guessed type __int64 c21(void);
// 18F2: using guessed type __int64 __fastcall c27();

//----- (0000000000001935) ----------------------------------------------------
__int64 c3()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c21(); ++i )
    v2 += c21();
  return v2;
}
// 1505: using guessed type __int64 c21(void);
// 1935: using guessed type __int64 __fastcall c3();

//----- (0000000000001978) ----------------------------------------------------
__int64 c38()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c12(); ++i )
    v2 += c21();
  return v2;
}
// 1505: using guessed type __int64 c21(void);
// 1548: using guessed type __int64 c12(void);
// 1978: using guessed type __int64 __fastcall c38();

//----- (00000000000019BB) ----------------------------------------------------
__int64 c8()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c12(); ++i )
    v2 += c12();
  return v2;
}
// 1548: using guessed type __int64 c12(void);
// 19BB: using guessed type __int64 __fastcall c8();

//----- (00000000000019FE) ----------------------------------------------------
__int64 c31()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c34(); ++i )
    v2 += c12();
  return v2;
}
// 1548: using guessed type __int64 c12(void);
// 158B: using guessed type __int64 c34(void);
// 19FE: using guessed type __int64 __fastcall c31();

//----- (0000000000001A41) ----------------------------------------------------
__int64 c6()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c34(); ++i )
    v2 += c34();
  return v2;
}
// 158B: using guessed type __int64 c34(void);
// 1A41: using guessed type __int64 __fastcall c6();

//----- (0000000000001A84) ----------------------------------------------------
__int64 c20()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c17(); ++i )
    v2 += c34();
  return v2;
}
// 158B: using guessed type __int64 c34(void);
// 1A84: using guessed type __int64 __fastcall c20();

//----- (0000000000001AC7) ----------------------------------------------------
__int64 c39()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c17(); ++i )
    v2 += c17();
  return v2;
}
// 1AC7: using guessed type __int64 __fastcall c39();

//----- (0000000000001B0A) ----------------------------------------------------
__int64 c9()
{
  unsigned __int64 i; // [rsp+0h] [rbp-10h]
  __int64 v2; // [rsp+8h] [rbp-8h]

  v2 = 0LL;
  for ( i = 0LL; i < c30(); ++i )
    v2 += c17();
  return v2;
}
// 1611: using guessed type __int64 c30(void);
// 1B0A: using guessed type __int64 __fastcall c9();

//----- (0000000000001B4D) ----------------------------------------------------
int __cdecl main(int argc, const char **argv, const char **envp)
{
  FILE *v3; // rbx
  __int64 v4; // rax
  int v5; // eax
  __int64 v7[40]; // [rsp+0h] [rbp-170h] BYREF
  unsigned int i; // [rsp+144h] [rbp-2Ch]
  __int64 v9; // [rsp+148h] [rbp-28h]
  __int64 v10; // [rsp+150h] [rbp-20h]
  __int64 v11; // [rsp+158h] [rbp-18h]

  setbuf(_bss_start, 0LL);
  qmemcpy(v7, &off_41A0, sizeof(v7));
  v11 = 0LL;
  v10 = 0LL;
  v9 = 0LL;
  for ( i = 0; i <= 0x13F; ++i )
  {
    v10 = (v10 << 8) + flag[i];
    if ( ++v9 == 8 )
    {
      v3 = _bss_start;
      v4 = v11++;
      v5 = ((__int64 (*)(void))v7[v4])();
      putc(v5 ^ v10, v3);
      v9 = 0LL;
      v10 = 0LL;
    }
  }
  return 0;
}
// 41A0: using guessed type __int64 (__fastcall *off_41A0)();

//----- (0000000000001C40) ----------------------------------------------------
void __fastcall _libc_csu_init(unsigned int a1, __int64 a2, __int64 a3)
{
  signed __int64 v4; // rbp
  __int64 i; // rbx

  init_proc();
  v4 = &_do_global_dtors_aux_fini_array_entry - &_frame_dummy_init_array_entry;
  if ( v4 )
  {
    for ( i = 0LL; i != v4; ++i )
      ((void (__fastcall *)(_QWORD, __int64, __int64))*(&_frame_dummy_init_array_entry + i))(a1, a2, a3);
  }
}
// 1140: using guessed type __int64 __fastcall frame_dummy(_QWORD, _QWORD, _QWORD);
// 3DE8: using guessed type __int64 (__fastcall *_frame_dummy_init_array_entry)();
// 3DF0: using guessed type __int64 (__fastcall *_do_global_dtors_aux_fini_array_entry)();

//----- (0000000000001CA4) ----------------------------------------------------
void term_proc()
{
  ;
}

// nfuncs=59 queued=49 decompiled=49 lumina nreq=0 worse=0 better=0
// ALL OK, 49 function(s) have been successfully decompiled
